Simpified travis ci config
/home/travis/build/center-key/generator-gulp-plugin/node_modules/w3cjs/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/degenerator/node_modules/ast-types/def/flow.js:251
  ].forEach(typeName => {
            ^^^^^^^^
SyntaxError: missing ) after argument list